name: News Mailer
on:
  schedule:
    - cron: "30 23 * * *"  # 매일 08:30 KST == 23:30 UTC(전일)
  workflow_dispatch: {}     # 수동 실행 버튼
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run mailer
        env:
          NEWS_KEYWORDS: "노조법, 파업"
          NEWS_RECENCY_DAYS: "1"
          MAIL_SENDER: "deukgu.kim@gmail.com"
          MAIL_RECIPIENTS: "deukgu.kim@gmail.com"
          SMTP_HOST: "smtp.gmail.com"
          SMTP_PORT: "465"
          SMTP_USER: "yourname@gmail.com"
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_SUBJECT_PREFIX: "[뉴스요약]"
        run: python news_mailer.py
